CC = g++
CFLAGS = -fopenmp -O3

hello: hello.cpp
	$(CC) $(CFLAGS) -o hello hello.cpp

ex1: ex1.cpp
	$(CC) $(CFLAGS) -o ex1 ex1.cpp

ex2: ex2.cpp
	$(CC) $(CFLAGS) -o ex2 ex2.cpp

clean: 
	rm -rf ex1 ex2 hello *~
